####################################################################################
###user test

###logud
POST http://localhost:7000/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJHcnVwcGU0Iiwic3ViIjoidXNlcjQyQGVtYWlsLmRrIiwiZXhwIjoxNzEzNjI5NjE4LCJlbWFpbCI6InVzZXI0MkBlbWFpbC5kayIsInJvbGVzIjoidXNlciJ9.5dBO_C5ilwEExgdbkZhLhYLTyjsV1yXzDvSUXk0VaHc


### rest password
POST http://localhost:7000/api/auth/reset-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJHcnVwcGU0Iiwic3ViIjoidXNlcjQyQGVtYWlsLmRrIiwiZXhwIjoxNzEzNjI5OTIzLCJlbWFpbCI6InVzZXI0MkBlbWFpbC5kayIsInJvbGVzIjoidXNlciJ9.QQt4Evrq9t1-_AIM_1GM_9Xgb6FEXOXISzeqDMD_U2s

{
"newPassword":"1234"
}


###user med email som id test
GET http://localhost:7000/api/users/user/user4@email.dk
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJHcnVwcGU0Iiwic3ViIjoiYWRtaW5AZW1haWwuZGsiLCJleHAiOjE3MTM2MjU2NzUsImVtYWlsIjoiYWRtaW5AZW1haWwuZGsiLCJyb2xlcyI6ImFkbWluIn0.WY7_XxF-KP-KqEbfCwHzeMUqKXL0h0pdihN41BDer9E
### alle bruger
GET http://localhost:7000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJHcnVwcGU0Iiwic3ViIjoiYWRtaW5AZW1haWwuZGsiLCJleHAiOjE3MTM2MjU2NzUsImVtYWlsIjoiYWRtaW5AZW1haWwuZGsiLCJyb2xlcyI6ImFkbWluIn0.WY7_XxF-KP-KqEbfCwHzeMUqKXL0h0pdihN41BDer9E


### oprette bruger
POST http://localhost:7000/api/auth/register
Content-Type: application/json

{
  "name": "admin",
  "email": "admin@email.dk",
  "phone": "12345678",
  "password": "1234"
}
###login
POST http://localhost:7000/api/auth/login
Content-Type: application/json

{
  "email": "user42@email.dk",
"password": "1234"
}


### Update a user
PUT http://localhost:7000/api/users/user/user42@email.dk
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJHcnVwcGU0Iiwic3ViIjoidXNlcjQyQGVtYWlsLmRrIiwiZXhwIjoxNzEzNjI4OTExLCJlbWFpbCI6InVzZXI0MkBlbWFpbC5kayIsInJvbGVzIjoidXNlciJ9.ccuvVURbCTS_H0KJ_oLPOGdPGkm2MbfKJdQ_g8OZ8LY

{
  "name": "Updated User",
  "email": "user42@email.dk",
  "phone": "98765432"
}

### Delete a user
DELETE http://localhost:7000/api/users/user/asd@asd.asd
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJHcnVwcGU0Iiwic3ViIjoiYWRtaW5AZW1haWwuZGsiLCJleHAiOjE3MTM2Mjg3NTYsImVtYWlsIjoiYWRtaW5AZW1haWwuZGsiLCJyb2xlcyI6ImFkbWluIn0._oqn-JXxODA4H252soJEMCW2ME20tvklQGgEWSg9KZo

####################################################################################
###event test

###oprete event
POST http://localhost:7000/api/events
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJHcnVwcGU0Iiwic3ViIjoiYWRtaW5AZW1haWwuZGsiLCJleHAiOjE3MTM2MjU2NzUsImVtYWlsIjoiYWRtaW5AZW1haWwuZGsiLCJyb2xlcyI6ImFkbWluIn0.WY7_XxF-KP-KqEbfCwHzeMUqKXL0h0pdihN41BDer9E


{
  "title": "Event4",
  "description": "This is event 4",
  "date": "2024-01-02",
  "time": "10:00:00",
  "duration": "120",
  "capacity": "100",
  "location": "Location 4",
  "image": "image1.png",
  "status": "ACTIVE"
}

### Get all events
GET http://localhost:7000/api/events
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJHcnVwcGU0Iiwic3ViIjoiYWRtaW5AZW1haWwuZGsiLCJleHAiOjE3MTM2MjY1NDUsImVtYWlsIjoiYWRtaW5AZW1haWwuZGsiLCJyb2xlcyI6ImFkbWluIn0.AzoWFQzuOY94VtD30QDhAdZrmnf3YdwW3qu0FszbwPw

### Get a single event
GET http://localhost:7000/api/events/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJHcnVwcGU0Iiwic3ViIjoiYWRtaW5AZW1haWwuZGsiLCJleHAiOjE3MTM2MjY1NDUsImVtYWlsIjoiYWRtaW5AZW1haWwuZGsiLCJyb2xlcyI6ImFkbWluIn0.AzoWFQzuOY94VtD30QDhAdZrmnf3YdwW3qu0FszbwPw

### Update an event
PUT http://localhost:7000/api/events/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJHcnVwcGU0Iiwic3ViIjoiYWRtaW5AZW1haWwuZGsiLCJleHAiOjE3MTM2MjY1NDUsImVtYWlsIjoiYWRtaW5AZW1haWwuZGsiLCJyb2xlcyI6ImFkbWluIn0.AzoWFQzuOY94VtD30QDhAdZrmnf3YdwW3qu0FszbwPw

{
  "title": "Updated Event",
  "description": "This is an updated event",
  "date": "2024-01-02",
  "time": "10:00:00",
  "duration": "120",
  "capacity": "100",
  "location": "Updated Location",
  "image": "updated_image.png",
  "status": "ACTIVE"
}

### Delete an event
DELETE http://localhost:7000/api/events/15
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJHcnVwcGU0Iiwic3ViIjoiYWRtaW5AZW1haWwuZGsiLCJleHAiOjE3MTM2MjY1NDUsImVtYWlsIjoiYWRtaW5AZW1haWwuZGsiLCJyb2xlcyI6ImFkbWluIn0.AzoWFQzuOY94VtD30QDhAdZrmnf3YdwW3qu0FszbwPw
####################################################################################
###registrations test

###alle registeringer
GET http://localhost:7000/api/registrations/

### vi giver event id 1 til user id 3 så event id i link og user id i body
POST http://localhost:7000/api/registrations/8
Content-Type: text/plain

Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJHcnVwcGU0Iiwic3ViIjoiYWRtaW5AZW1haWwuZGsiLCJleHAiOjE3MTM2MjU2NzUsImVtYWlsIjoiYWRtaW5AZW1haWwuZGsiLCJyb2xlcyI6ImFkbWluIn0.WY7_XxF-KP-KqEbfCwHzeMUqKXL0h0pdihN41BDer9E

6
### se kun bruger registering ud fra id
GET http://localhost:7000/api/registrations/id/2

### selette registering ud fra id
DELETE http://localhost:7000/api/registrations/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJHcnVwcGU0Iiwic3ViIjoiYWRtaW5AZW1haWwuZGsiLCJleHAiOjE3MTM2MjU2NzUsImVtYWlsIjoiYWRtaW5AZW1haWwuZGsiLCJyb2xlcyI6ImFkbWluIn0.WY7_XxF-KP-KqEbfCwHzeMUqKXL0h0pdihN41BDer9E

###
