POST http://localhost:7000/api/auth/register

{
"name": "test2",
"email": "test2@gmail.com",
"phone": "00000000",
"password": "test123"
}

###

POST http://localhost:7000/api/auth/login

{
"email": "test2@gmail.com",
"password": "test123"
}

###
POST http://localhost:7000/api/auth/reset-password
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJUaG9tYXMgSGFydG1hbm4iLCJzdWIiOiJ0ZXN0MkBnbWFpbC5jb20iLCJleHAiOjE3MTI0NDMyMjYsImVtYWlsIjoidGVzdDJAZ21haWwuY29tIiwicm9sZXMiOiJ1c2VyIn0.bzVsCn0GvhaBOuLuvMUk4dtLJ6YGRfekh3Pm1OzfOuk

{
  "newPassword": "newSecurePassword123"
}

###
POST http://localhost:7000/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJHcnVwcGU0Iiwic3ViIjoidGVzdDJAZ21haWwuY29tIiwiZXhwIjoxNzEzNjIyMjczLCJlbWFpbCI6InRlc3QyQGdtYWlsLmNvbSIsInJvbGVzIjoidXNlciJ9.JOoKE5ts2t4R5Whl177XqhDwG6XTRjcO5mXYlpez2xU
