POST http://localhost:7000/api/auth/register

{
"name": "test2",
"email": "test2@gmail.com",
"password": "test123",
"phone": "00000000"
}

###

POST http://localhost:7000/api/auth/login

{
"email": "test2@gmail.com",
"password": "test123"
}

###
POST http://localhost:7000/api/auth/reset-password
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJUaG9tYXMgSGFydG1hbm4iLCJzdWIiOiJ0ZXN0MkBnbWFpbC5jb20iLCJleHAiOjE3MTI0NDMyMjYsImVtYWlsIjoidGVzdDJAZ21haWwuY29tIiwicm9sZXMiOiJ1c2VyIn0.bzVsCn0GvhaBOuLuvMUk4dtLJ6YGRfekh3Pm1OzfOuk

{
  "newPassword": "newSecurePassword123"
}

###
POST http://localhost:7000/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJUaG9tYXMgSGFydG1hbm4iLCJzdWIiOiJ0ZXN0MkBnbWFpbC5jb20iLCJleHAiOjE3MTI0NDUzMTgsImVtYWlsIjoidGVzdDJAZ21haWwuY29tIiwicm9sZXMiOiJ1c2VyIn0.Rr0Nmk3yub2eZtfzsUqdGGit4bylZcTmQXmSt3ZIljE
